version: '2'
services:
  dmall-shipping-service:
    image: '${DMALL_DOCKER_REGISTRY}/dmall/shipping-service:${BUILD_NUMBER}'
    ports:
      - "8081:8081"
    external_links:
        - dmall-config-server/dmall-config-server:dmall-config-server
        - dmall-registry-server/dmall-registry-server:dmall-registry-server
