spring:
  application:
    name: shipping-service

server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 2 #契约更新间隔
    lease-expiration-duration-in-seconds: 4 #契约过期时间
  client:
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true